version: "3"

vars:
    APP: chainer

tasks:
    proto:
        cmds:
            - |
                protoc --go_out=. --go_opt=paths=source_relative \
                --go-grpc_out=. --go-grpc_opt=paths=source_relative \
                proto/*.proto

    build:
        cmds:
            - go build -o bin/{{.APP}}

    run:
        cmds:
            - go run cmd/main.go

    test:
        cmds:
            - go test -v ./...
